name: Naver Bot Run

on:
  schedule:
    - cron: '*/3 * * * *' # 3분마다 자동 실행
  workflow_dispatch: # 수동 실행 버튼 생성

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager requests
      - name: Run Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python naver_bot.py
